-- Seed initial pour Veille Kiné Sport.
-- À exécuter après schema.sql, une seule fois (idempotent : on conflict do nothing).

insert into profile (id, data) values (1, $${"diplome":"Diplôme de Masseur-Kinésithérapeute, option imagerie et sport","experience":"Post-diplôme","langues":["français","anglais","espagnol"],"experiencesTerrain":["Stage en cabinet","Stage club de rugby","Aides ponctuelles en compétitions et clubs de rugby","Évaluations biomécaniques et complètes avec imagerie"],"mobilite":"Prêt à déménager, pas de visa de travail direct (hors UE/Schengen selon le pays)","sportsCibles":["Football","Basketball","Rugby","Football américain","Golf","Sport mécanique (F1, MotoGP)"],"paysPrioritaires":["France","Suisse","Angleterre","Irlande","États-Unis","Italie","Monaco","Espagne","Canada"],"paysHorsZone":"À remonter quand même si offre exceptionnelle, avec étiquette 'hors zone prioritaire'","objectif":"Poste dans un club/équipe de grande ligue reconnue ou une université sportive prestigieuse (ex. NCAA D1)"}$$::jsonb)
on conflict (id) do nothing;

-- Seed généré depuis les offres de démarrage du prototype (veille-kine-sport.jsx).
-- Objectif : ne pas repartir d'un dashboard vide au premier déploiement.
-- Idempotent grâce à `on conflict (id) do nothing`.

insert into offers (id, titre, club, pays, sport, niveau, genre, resume, lien, source, date_publication, date_trouvee, hors_zone_prioritaire, statut, note, expire, vu, emaile) values
  ('o1443ku', 'Senior MSK Physiotherapist', 'McLaren Racing (F1)', 'Angleterre', 'Sport mécanique', 'Pro', 'Mixte / non précisé', 'Kinésithérapeute MSK senior au sein du McLaren Performance Hub, pour l''évaluation, le traitement et la rééducation musculosquelettique du personnel de l''écurie, en équipe pluridisciplinaire.', 'https://fluidjobs.com/jobs/510962956-senior-msk-physiotherapist', 'Fluid Jobs', '2026-07-05', '2026-07-12', false, 'Nouveau', '', false, true, true),
  ('or6tzbc', 'Physiotherapist — Men''s First Team', 'Crystal Palace FC', 'Angleterre', 'Football', 'Pro', 'Masculin', 'Kinésithérapeute pour l''équipe première du club de Premier League : bilans, traitements et rééducation des joueurs, avec présence en match et travail au sein du staff médical.', 'https://jobs4football.com/job/physiotherapist-mens-first-team/', 'Jobs4football', '2026-06-12', '2026-07-12', false, 'Nouveau', '', false, true, true),
  ('ofc8fza', 'Talent Management (Loans) Physiotherapist', 'Newcastle United FC', 'Angleterre', 'Football', 'Pro', 'Masculin', 'Kinésithérapeute référent pour le suivi médical des joueurs de Newcastle United prêtés dans d''autres clubs, en coordination avec le staff médical central du club.', 'https://jobsinfootball.com/categories/physiotherapist/', 'Jobs in Football', null, '2026-07-12', false, 'Nouveau', '', false, true, true),
  ('owdv8nn', 'Academy Physiotherapist / Sports Therapist (U18s)', 'Cardiff City FC', 'Pays de Galles', 'Football', 'Semi-pro', 'Masculin', 'Kinésithérapeute/thérapeute du sport pour l''académie U18 du club : encadrement médical des jeunes joueurs à l''entraînement et en match. Clôture des candidatures le 23/07/2026.', 'https://irecruit.efl.com/vacancies/vacancy-search-results.aspx', 'EFL iRecruit', null, '2026-07-12', true, 'Nouveau', '', false, true, true),
  ('onney1g', 'Athletic Trainer / Physical Therapist', 'New York Jets (NFL)', 'États-Unis', 'Football américain', 'Pro', 'Masculin', 'Poste combiné athletic trainer / kinésithérapeute pour la franchise NFL. Exige une double qualification ATC/DPT américaine et une expérience en football universitaire ou professionnel — licence et visa de travail américains nécessaires.', 'https://www.teamworkonline.com/football-jobs/footballjobs/new-york-jets/athletic-trainer-physical-therapist-2120860', 'TeamWork Online', null, '2026-07-12', false, 'Nouveau', '', false, true, true),
  ('oot3x34', 'Physical Therapist (Development)', 'Seattle Sounders FC (MLS)', 'États-Unis', 'Football', 'Semi-pro', 'Masculin', 'Kinésithérapeute pour l''effectif de développement (Tacoma Defiance et académie) du club MLS : rééducation post-chirurgicale et prévention des blessures. Licence de l''État de Washington et visa de travail requis.', 'https://www.teamworkonline.com/soccer-jobs/seattle-sounders/seattle-sounders/physical-therapist-development-seattle-sounders-fc-2165024', 'TeamWork Online', null, '2026-07-12', false, 'Nouveau', '', false, true, true),
  ('o6kzq6l', 'Lead Physical Therapist / Athletic Trainer', 'Las Vegas Aces (WNBA)', 'États-Unis', 'Basketball', 'Pro', 'Féminin', 'Responsable de la construction du programme de médecine du sport de la franchise WNBA, sous la supervision du directeur médical. Licence et visa de travail américains nécessaires.', 'https://www.teamworkonline.com/basketball-jobs/nbateamjobs/wnba-las-vegas/lead-physical-therapist-athletic-trainer-2034980', 'TeamWork Online', null, '2026-07-12', false, 'Nouveau', '', false, true, true),
  ('oysqlha', 'Head Athletic Trainer, Football', 'Rice University (NCAA D1)', 'États-Unis', 'Football américain', 'Universitaire', 'Masculin', 'Rice University recherche un athletic trainer/kinésithérapeute responsable du programme médical de son équipe de football américain universitaire (NCAA Division I), en lien avec le staff médical de l''établissement.', 'https://collegesports.jobs/', 'CollegeSports.jobs (NCAA Market)', '2026-07-10', '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('om8rm3e', 'Academy Physiotherapist (U9–U16, Men''s Academy)', 'Bristol City FC', 'Angleterre', 'Football', 'Semi-pro', 'Masculin', 'Bristol City FC recrute un kinésithérapeute pour piloter le suivi médical de son académie masculine (U9-U16), en encadrant l''équipe de soins et les intervenants de la Foundation et Youth Development Phase.', 'https://jobsinfootball.com/jobs/academy-physiotherapist-jobs/', 'Jobs in Football', null, '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('obspcm8', 'Women''s Team Graduate Physiotherapist', 'AFC Bournemouth', 'Angleterre', 'Football', 'Pro', 'Féminin', 'AFC Bournemouth propose un poste de kinésithérapeute diplômé au sein de son équipe féminine, pour contribuer à la prévention des blessures, à l''évaluation et à la rééducation des joueuses sous supervision d''un membre senior du staff médical.', 'https://jobsinfootball.com/jobs/physiotherapist-jobs/', 'Jobs in Football', '2026-05-07', '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('o5otrbs', 'Kinésithérapeute (Centre Médical de Clairefontaine)', 'Fédération Française de Football (FFF)', 'France', 'Football', 'Fédéral', 'Mixte / non précisé', 'La FFF recrute un kinésithérapeute en CDI pour le Centre Médical de Clairefontaine, au service de la rééducation des athlètes de haut niveau et des jeunes du centre de formation, avec encadrement de stagiaires.', 'https://recrutement.fff.fr/jobs-offers/136865168.html', 'FFF Recrutement', null, '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('oo2qa1h', 'MLS Academy Athletic Therapist', 'Vancouver Whitecaps FC', 'Canada', 'Football', 'Semi-pro', 'Masculin', 'Le Vancouver Whitecaps FC recrute un athletic therapist pour seconder le responsable médical de son académie MLS : prévention, évaluation, traitement et rééducation des jeunes joueurs, en lien avec le staff sportif du club.', 'https://www.whitecapsfc.com/jobs/athletic-therapist-mls-academy', 'Whitecaps FC (site officiel)', null, '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('on05aqe', 'Athletic Therapist', 'Toronto Raptors 905 (NBA G League) / MLSE', 'Canada', 'Basketball', 'Semi-pro', 'Masculin', 'MLSE recherche un athletic therapist pour le Raptors 905 (antenne G League des Toronto Raptors), en coordination avec les équipes médicales des Raptors NBA pour la gestion de la santé et de la performance des joueurs.', 'https://ca.indeed.com/q-mlse-l-toronto,-on-jobs.html', 'MLSE / Indeed', null, '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('od7ekkf', 'Manual Therapist', 'Seattle Kraken (NHL)', 'États-Unis', 'Hockey', 'Pro', 'Masculin', 'Les Seattle Kraken (NHL) recrutent un thérapeute manuel pour le service de médecine du sport de l''équipe, en collaboration avec les athletic trainers, médecins et préparateurs physiques pour optimiser récupération et performance des joueurs.', 'https://www.teamworkonline.com/hockey-jobs/seattle-kraken-/nhl-seattle-jobs/manual-therapist-2168159', 'TeamWork Online', '2026-04-23', '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('om7fmjr', 'Academy Physiotherapist (Casual)', 'Arsenal FC', 'Angleterre', 'Football', 'Semi-pro', 'Masculin', 'Arsenal FC recrute un kinésithérapeute vacataire pour la couverture médicale pitch-side de son académie (Hale End, U9-U16), en soutien du kinésithérapeute référent et du responsable de la performance académie.', 'https://jobsinfootball.com/jobs/?q=physiotherapy', 'Jobs in Football', '2026-04-26', '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('ora7yz5', 'First Team Physiotherapist (Arsenal Women)', 'Arsenal FC (AWFC)', 'Angleterre', 'Football', 'Pro', 'Féminin', 'Arsenal recrute un kinésithérapeute pour l''équipe première féminine, en soutien des kinésithérapeutes performance et santé féminine, pour la prise en charge médicale au quotidien et les jours de match.', 'https://jobsinfootball.com/company/41969/arsenal-fc/', 'Jobs in Football', null, '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('oshknb2', 'Minor League Physical Therapist', 'Baltimore Orioles (MLB)', 'États-Unis', 'Baseball', 'Semi-pro', 'Masculin', 'Les Baltimore Orioles recrutent un kinésithérapeute pour leur filière Minor League, en interaction quotidienne avec le staff de terrain, les médecins de l''équipe et le head athletic trainer pour la rééducation des jeunes joueurs.', 'https://www.teamworkonline.com/baseball-jobs/orioles-jobs/baltimore-orioles-jobs/minor-league-physical-therapist-2099388', 'TeamWork Online', null, '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('o26zgdi', 'Sports Physical Therapist', 'Los Angeles Sparks (WNBA)', 'États-Unis', 'Basketball', 'Pro', 'Féminin', 'Les LA Sparks recherchent un kinésithérapeute du sport pour l''évaluation, la rééducation et la gestion du retour au jeu des joueuses WNBA, en lien avec le directeur santé & performance et le staff de performance.', 'https://www.teamworkonline.com/basketball-jobs/nbateamjobs/los-angeles-sparks/sports-physical-therapist-2163480', 'TeamWork Online', '2026-03-23', '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('olu7rpd', 'Physical Therapist (NBA / G League dual role)', 'Toronto Raptors (NBA) / MLSE', 'Canada', 'Basketball', 'Pro', 'Masculin', 'MLSE recrute un kinésithérapeute pour les Toronto Raptors, avec une double couverture NBA et G League, au sein d''une équipe santé & performance pluridisciplinaire (médecins, athletic trainers, préparateurs physiques).', 'https://ca.indeed.com/q-toronto-maple-leafs-mlse-l-ontario-jobs.html', 'MLSE / Indeed', '2026-05-14', '2026-07-13', false, 'Nouveau', '', false, true, true),
  ('olz1zo8', 'Sessional Physiotherapist (Academy, WSLA, RTC, Foundation)', 'Chelsea FC', 'Angleterre', 'Football', 'Semi-pro', 'Mixte / non précisé', 'Chelsea FC recrute un kinésithérapeute vacataire pour couvrir l''académie masculine, la filière féminine WSLA, les centres régionaux de talents (RTC) et la Foundation, en soirée et le week-end lors des entraînements et matchs.', 'https://jobsinfootball.com/job/126838/sessional-physiotherapist/', 'Jobs in Football', null, '2026-07-14', false, 'Nouveau', '', false, true, true),
  ('oxfj7kq', 'Physical Therapist', 'Vegas Golden Knights (NHL)', 'États-Unis', 'Hockey', 'Pro', 'Masculin', 'Les Vegas Golden Knights recrutent un kinésithérapeute rattaché au département Performance & Médecine, chargé de la gestion des blessures musculosquelettiques, de la rééducation et du retour au jeu, sous la responsabilité du head athletic trainer.', 'https://www.teamworkonline.com/hockey-jobs/vegas-golden-knights/vegas-nhl/physical-therapist-2164993', 'TeamWork Online', null, '2026-07-16', false, 'Nouveau', '', false, true, true),
  ('oayhdsj', 'Performance Therapist', 'San Jose Sharks (NHL)', 'États-Unis', 'Hockey', 'Pro', 'Masculin', 'Les San Jose Sharks recherchent un kinésithérapeute pour leur modèle intégré performance/médecine : rééducation aiguë, prévention des blessures, thérapie manuelle et coordination avec les coachs de performance et le staff médical au quotidien.', 'https://www.teamworkonline.com/hockey-jobs/sharkssports/san-jose-sharks/performance-therapist-2166187', 'TeamWork Online', null, '2026-07-16', false, 'Nouveau', '', false, true, true),
  ('oeitybi', 'Physical Therapist', 'Chicago Sky (WNBA)', 'États-Unis', 'Basketball', 'Pro', 'Féminin', 'Les Chicago Sky recrutent un kinésithérapeute pour la rééducation, la récupération et l''optimisation du mouvement des joueuses tout au long de la saison WNBA, en lien avec la Directrice Santé & Performance et le staff médical.', 'https://www.teamworkonline.com/basketball-jobs/nbateamjobs/chicago-sky/physical-therapist-2147563', 'TeamWork Online', '2025-12-17', '2026-07-17', false, 'Nouveau', '', false, true, true),
  ('ok5d2bx', 'Academy Physiotherapist - Women''s Football', 'Everton Football Club', 'Angleterre', 'Football', 'Semi-pro', 'Féminin', 'Everton FC recrute un kinésithérapeute pour la filière féminine de son académie, en charge de la prévention, de l''évaluation et de la rééducation des jeunes joueuses, en lien avec le staff médical du club.', 'https://www.linkedin.com/jobs/view/4438003139/', 'LinkedIn (alerte email)', '2026-07-14', '2026-07-21', false, 'Nouveau', '', false, true, true),
  ('o3hdgpm', 'England Rugby Women''s Pathway U21 Lead Physiotherapist', 'England Rugby (RFU)', 'Angleterre', 'Rugby', 'Fédéral', 'Féminin', 'La Fédération anglaise de rugby recrute un kinésithérapeute référent pour la filière féminine U21, chargé du suivi médical et de la préparation des joueuses dans le parcours de performance vers l''équipe senior.', 'https://www.linkedin.com/jobs/view/4438096622/', 'LinkedIn (alerte email)', '2026-07-15', '2026-07-21', false, 'Nouveau', '', false, true, true),
  ('o27h7vt', 'Assistant Athletic Trainer, Academy', 'Los Angeles Football Club (LAFC)', 'États-Unis', 'Football', 'Semi-pro', 'Masculin', 'Le LAFC (MLS) recrute un athletic trainer assistant pour son académie, chargé de la prévention des blessures, des soins d''urgence et de la rééducation des jeunes joueurs en formation.', 'https://www.linkedin.com/jobs/view/4441688701/', 'LinkedIn (alerte email)', '2026-07-17', '2026-07-21', false, 'Nouveau', '', false, true, true)
on conflict (id) do nothing;
